exclude = { glob = ["testing file/**", "tests/**.rpy"] }

#:schema https://www.schemastore.org/prek.json
[[repos]]
repo = "builtin"
hooks = [
  { id = "check-merge-conflict" },
  { id = "check-added-large-files" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
  { id = "mixed-line-ending" },
  { id = "check-yaml" },
  { id = "check-json" },
  { id = "check-toml" },
]

[[repos]]
hooks = [
  {
    id = "ruff-check",
    args = [
      "--fix",
      "--select=E,F,UP,B,SIM,I",
    ]
  },
  { id = "ruff-format" },
]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.11"
